name: production - lightsail
variables:
  - name: checkin
    value: 13.213.228.82
  - name: baseUrl
    value: http://13.213.228.82/api/v1
  - secret: true
    name: auth_token
  - secret: true
    name: admin_token
  - name: apiOrigin
    value: ""
  - name: frontendOrigin
    value: "http://localhost:5173"
  - name: browser_admin_email
    value: "admin@checkin.app"
  - name: browser_admin_password
    secret: true
  - name: browser_cookie
    value: ""
  - name: xsrf_token
    value: ""
  - name: deletion_phone
    value: ""
  - name: manual_deletion_phone
    value: ""
  - name: deletion_password
    secret: true
